config/routes.rb
Rails.application.routes.draw do
  
  devise_for :logins, controllers: {
      registrations: 'login/registrations'
  }

  root 'welcome#index'

  get '/dashboard' => 'dashboard#index'
  resources :dashboard
  
  resources :users

  get '/activities/week'
  get '/activities/month'
  get '/activities/year'
  resources :activities

  get '/friendships' => 'friendships#index'
  get '/friendships/invite'
  get '/friendships/confirm'
  get '/friendships/delete'
  get '/friendships/cancel'
  get '/friendships/reject'
  resources :friendships

  resources :maps

  resources :sports
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :birthday, :locality, presence: true
  belongs_to :login
  has_many :activities, dependent: :destroy
  has_many :sports, :through => :activities
  has_many :maps, :through => :activities
  has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_login!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    if not params[:searchq].blank?
      @users = @users.where("name like ?", "%#{params[:searchq]}%")
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @activities = Activity.where(user_id: params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.login = current_login
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :gender,   :birthday, :locality, :photo, :login_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!--
  <div class="field">
    <%= f.label :login_id %><br>
    <%= f.number_field :login_id %>
  </div>
-->

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select :gender, ['Male','Female'], :prompt=>'Select Gender' %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday , :start_year => 1920, :end_year => Date.today.year+1 %>
  </div>
  <div class="field">
    <%= f.label :locality %><br>
    <%= f.text_field :locality %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<form class = "SearchForm" action="/users" method="get">
  <%= form_tag('/users', :method => 'get' ) do %>
      <label for="searchbox">Search:</label>
      <input id="searchbox" type = "text" name = "searchq">
      <input type="submit" value="GO!">
  <% end %>
</form>

<table class = "DataTable">
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td>
        <% if current_login.user.id == user.id %>
            <%= link_to 'Edit', edit_user_path(user) %>
        <% end %>
        </td>
        </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id="photoContainer">
  <img id="userPhoto" src="<%= @user.photo %>" alt="No photo" style="width:150px; height:auto">
</div>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Locality:</strong>
  <%= @user.locality %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.login.email %>
</p>
<% if current_login.user.id != @user.id and Friendship.where(user_id: current_login.user.id, friend_id: @user.id).blank? %>
  <%= link_to 'Add Friend', friendships_invite_path(id: @user.id) %>
<% end %>
<% if current_login == @user.login %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back', users_path %>

<br><br>
<h1><%= @user.name %> Activities</h1>
<% if @activities.blank? %>
    <p>No activities found</p>
<% else %>
    <table>
      <thead>
      <tr>
        <th>Name</th>
        <th>Sport</th>
        <th>User</th>
        <th>Start date</th>
        <th>Duration (min)</th>
        <th>Distance (m)</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @activities.each do |activity| %>
          <tr>
            <td><%= activity.name %></td>
            <td><%= activity.sport.name %></td>
            <td><%= activity.user.name %></td>
            <td><%= activity.start_date %></td>
            <td><%= activity.duration %></td>
            <td><%= activity.distance %></td>
            <td><%= link_to 'Show', activity %></td>
            <% if activity.user_id == current_login.user.id %>
                <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
                <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>