config/routes.rb
Rails.application.routes.draw do
  
  devise_for :logins, controllers: {
      registrations: 'login/registrations'
  }

  root 'welcome#index'

  get '/dashboard' => 'dashboard#index'
  resources :dashboard
  
  resources :users

  get '/activities/week'
  get '/activities/month'
  get '/activities/year'
  resources :activities

  get '/friendships' => 'friendships#index'
  get '/friendships/invite'
  get '/friendships/confirm'
  get '/friendships/delete'
  get '/friendships/cancel'
  get '/friendships/reject'
  resources :friendships

  resources :maps

  resources :sports
  

  

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  validates :user_id, :friend_id, :state, presence: true
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_login!

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.where(user_id: current_login.user.id, state: 'Confirmed')
    @pendingFriendships = Friendship.where(user_id: current_login.user.id, state: 'Pending').order('created_at ASC')
    @receivedFriendships = Friendship.where(friend_id: current_login.user.id, state: 'Pending').order('created_at ASC')
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show

  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = Friendship.create(friendship_params)
    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  def invite
    Friendship.create(user_id: current_login.user.id, friend_id: params[:id], state: 'Pending')
    redirect_to friendships_path
  end

  def confirm
    Friendship.create(user_id: current_login.user.id, friend_id: params[:id], state: 'Confirmed')
    friend = Friendship.where(user_id: params[:id], friend_id: current_login.user.id).first
    friend.state = 'Confirmed'
    friend.save!
    redirect_to friendships_path
  end

  def delete
    @deleteFriend = Friendship.where(:user_id => current_login.user.id, :friend_id => params[:id_f])
    Friendship.delete(@deleteFriend)
    @deleteFriend = Friendship.where(:user_id => params[:id_f], :friend_id => current_login.user.id)
    Friendship.delete(@deleteFriend)
    redirect_to friendships_path
  end

  def cancel
    @deleteFriend = Friendship.where(:user_id => current_login.user.id, :friend_id => params[:id_f])
    Friendship.delete(@deleteFriend)
    redirect_to friendships_path
  end

  def reject
    @deleteFriend = Friendship.where(:user_id => params[:id_f], :friend_id => current_login.user.id)
    Friendship.delete(@deleteFriend)
    redirect_to friendships_path
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to friendships_url, notice: 'Friendship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :state)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h2>Friendships</h2>
<table>
  <% if @friendships.blank? %>
    <p> No friends found </p>
  <% else %>
  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= link_to friendship.friend.name, friendship.friend %> - <%= link_to 'Delete', friendships_delete_path(id_f: friendship.friend.id) %> </td>
      </tr>
    <% end %>

  </tbody>
  <% end %>
</table>
<br>

<h2>Sent Friendship Requests</h2>
<table>
  <% if @pendingFriendships.blank? %>
    <p> No requests found </p>
  <% else %>
  <tbody>
    <% @pendingFriendships.each do |friendship| %>
      <tr>
        <td><%= link_to friendship.friend.name, friendship.friend %> - <%= link_to 'Cancel', friendships_cancel_path(id_f: friendship.friend.id) %></td>
      </tr>
    <% end %>
  </tbody>
  <% end %>
</table>
<br>

<h2>Received Friendship Requests</h2>
<table>
  <% if @receivedFriendships.blank? %>
    <p> No requests found </p>
  <% else %>
  <tbody>
    <% @receivedFriendships.each do |friendship| %>
      <tr>
        <td><%= link_to friendship.user.name, friendship.user %> - <%= link_to 'Accept', friendships_confirm_path(id: friendship.user.id) %> |
          <%= link_to 'Reject', friendships_reject_path(id: friendship.friend.id) %>

        </td>
      </tr>
    <% end %>
  </tbody>
  <% end %>
</table>
<br>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @friendship.state %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>