config/routes.rb
Rails.application.routes.draw do
  
  devise_for :logins, controllers: {
      registrations: 'login/registrations'
  }

  root 'welcome#index'

  get '/dashboard' => 'dashboard#index'
  resources :dashboard
  
  resources :users

  get '/activities/week'
  get '/activities/month'
  get '/activities/year'
  resources :activities

  get '/friendships' => 'friendships#index'
  get '/friendships/invite'
  get '/friendships/confirm'
  get '/friendships/delete'
  get '/friendships/cancel'
  get '/friendships/reject'
  resources :friendships

  resources :maps

  resources :sports
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <title>Sports Activity App</title>
  <meta name="description" content="Sports App Web Site">
  <meta name="author" content="Pedro Martins">
  <style>
    head { text-decoration-color: white }
    body {  padding-right: 10px; padding-bottom: 20px; padding-left: 10px; margin: auto; width:85% }
    table { text-emphasis-style: triangle; text-align: center }
    th { padding-top: 10px }
    td {  padding-right: 20px }
    footer { background-color: orangered; padding-left:10px;  text-align: left ; color: black ; clear: both }
    li { font-size: large; display: inline-block ; list-style-type: none }
    #Menu { position: static; padding-top: 1px ; padding-bottom: 1px ; background-color: orangered }
    #PageContent { clear: both; padding-top: 25px; padding-right: 50px; padding-bottom: 50px; padding-left: 50px;
      background-color: white; width: auto; min-height: 200px }
    .LoginInfoDiv { padding-right: 5px; padding-bottom: 5px; padding-left: 25px;
      text-align: right;
    }
    .SearchForm {
      margin-left: 10px; margin-top: 10px
    }
    .DataTable {
      margin-left: 10px; margin-top: 10px
    }
  </style>
</head>
<body>

<% if login_signed_in? %>
    <div class = "LoginInfoDiv">
      User:<%= current_login.user.name %>
      <%= link_to 'Edit profile', edit_login_registration_path %> |
      <%= link_to 'Logout', destroy_login_session_path, method: :delete %>
    </div>
<% else %>
    <div class = "LoginInfoDiv">
      <%= link_to 'Sign up', new_login_registration_path %> |
      <%= link_to 'Login', new_login_session_path %>
    </div>
<% end %>

<% if login_signed_in? %>
    <div id ="Banner">
    </div>

     <div id = "Menu">
      <ul>
        <h1>Sports App</h1>
          <% if current_login.user != nil %>
              <li><%= link_to 'Dashboard', dashboard_path, method: :get %></li>
              <li><%= link_to 'Activities', activities_path, method: :get %></li>
              <li><%= link_to 'My Friends', friendships_path, method: :get %></li>
              <li><%= link_to 'Users', users_path, method: :get %></li>
          <% else %>
          <% end %>
      </ul>
    </div>
<% end %>
<div>
  <div id = "PageContent">
    <%= yield %>
  </div>
</div>
</body>
<footer>
  <p>DAWeb 14/15 | Authors: Pedro Franco e Pedro Martins</p>
</footer>
</html>